### ISSUE TITLE
Dataset Format - How to Prepare the Dataset?

### ISSUE THREAD

**Issue by JacCubk** [MjdMahasneh/MLMT-CNN-for-object-detection-and-segmentation-in-multi-layer-and-multi-spectral-images#1]
Hello! 

Thank you very much for providing such a great work. 

I'm highly interested in your ideas. However, I'm a novice in the field of hyperspectral image processing. I would like to use your network to train my own dataset. Currently, I have a dataset of size 1024*1024*101 (Height, Width, Channels), but I'm unsure about how to prepare the dataset. Could you please guide me on the structure of the dataset files? 

Thank you once again! 

Wishing you even greater success ahead.

**Comment by MjdMahasneh** [comment]
Although this isn't an issue, but I will try to provide some tips for your questions in hope to help.

It depends on how you want to handle input images, typically, CNNs are trained with RGB images, so the first layer of the network expects 3 channels, R G, and B. Accordingly when dealing with 101 channels, you need to change the set up of you NN and data handling routines to account for that. That's the technical part. For the practical part, 101 channels/bands are way too much to feed a CNN on common available GPUs, so what you could possibly do is either pick some channels that are representative of the target task (maybe by doing some importance analysis of some sort), or by reducing the number of channels using some function to combine them. There might be typical approaches for handling such cases, so it's worth researching. You may also want to downsample the image from 1024 to something smaller.

Mind that finding the best setup is more of a trial and error (starting from a reasonable guess).

Hope this helps.
